feat: npm-publish.yml 调整——判断当前版本号已经被发布时，脚本抛出错误提示并终止

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -26,7 +26,8 @@ jobs:
             echo "allow=true" >> $GITHUB_OUTPUT
           else
             echo "allow=false" >> $GITHUB_OUTPUT
-            echo "发布失败！${{env.NPM_PACKAGE_NAME}}的${{env.NPM_PACKAGE_VERSION}}版本已经发布！请更新版本号！！"
+            echo "::error title=发布失败::${{env.NPM_PACKAGE_NAME}}的${{env.NPM_PACKAGE_VERSION}}版本已经发布！请更新版本号！！"
+            exit 1
           fi
 
   lint-test:
